# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig_name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=1000)),
                ('co_ordinator', models.CharField(max_length=250)),
                ('conductors', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('topic_gist', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('sig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_sig.Sig')),
            ],
        ),
    ]
