# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_sig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='sig_logo',
            field=models.CharField(default='~\\Desktop\\web-d.png', max_length=1000),
            preserve_default=False,
        ),
    ]
