# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_sig', '0002_sig_sig_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='co_ordinator',
            field=models.CharField(default='Rahul Bothra', max_length=250),
            preserve_default=False,
        ),
    ]
