# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_sig', '0003_sig_co_ordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='created',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='modified',
        ),
    ]
